mqtt:
  host: 192.168.70.62
  port: 1883
  keepalive_s: 30
  qos: 0
  topic_prefix: beam_dubins
  target_topic: aoa/uav_center/+/uav_info

geodesy:
  origin_latitude_deg: 34.01396246
  origin_longitude_deg: 116.92349937
  origin_altitude_m: 0.0
  altitude_reference: ellipsoid

target:
  publish_tf: true
  timeout_ms: 5000

bridge:
  # target UAV 从 uav_caster/uavs_information 发现
  target_uav_topic: uav_caster/uavs_information
  target_uav_filter: "SIL"
  # own UAV 从 aoa/uav_center/fst_info 发现
  own_uav_topic: aoa/uav_center/fst_info
  own_uav_filter: "NOCON"

waypoint:
  default_speed_mps: 50.0